### PR TITLE
Initial sequelize connection

### PR DESCRIPTION
**Pull request by j-tirelli**
@harsh-vikram-singh @16qeddy Could you please review this for pull?

### CODE REVIEW

**Comment by 16qeddy** [comment]
looks good! glad you're enjoying the sequalize!

**Comment by harsh-vikram-singh** [comment]
Hey @j-tirelli you might want to look at adding a .env file, and read the parameters like AWS keys, db details, ports etc from there

**Comment by j-tirelli** [comment]
I think you are right @harsh-vikram-singh I made changes accordingly. Could you please review again?

**Comment by harsh-vikram-singh** [comment]
Looks good!

**Review by harsh-vikram-singh — APPROVED** [review]
Looks good.

**Pull request merged**
